baseURL = 'https://gzttk.org/'
languageCode = 'en-us'
title = 'DevOps and Locksmith'
theme = "blackburn"
pluralizelisttitles = "false"

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
   [[menu.main]]
    name = "Posts categories"
    pre = "<i class='fas fa-bars fa-fw'></i>"
    weight = 4
    url = "/categories/"
  [[menu.main]]
    name = "Posts tags"
    pre = "<i class='fas fa-hashtag fa-fw'></i>"
    weight = 4
    url = "/tags/"
  [[menu.main]]
    name = "Contacts"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 4
    url = "/contacts/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  #twitter = "*"

  ## SNS career oriented
  linkedin = "andrii-horobchenko-4a32bb1b8"

  ## SNS news
  reddit = "YTsshfd8H5rb"
  #hackernews = "*"

  ## Techie
  github = "sudores"

  ## Other
  keybase  = "teterds"
  telegram = "tetrds"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
# order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "master"
# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://devopsandlocksmith-website-bucket?region=us-east-1"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
cloudFrontDistributionID = "E3A8P8HW9YFHOR"
